# ===============================
# SERVER & NETWORK CONFIGURATION
# ===============================
server.port=8080
  # Allows other devices on your Wi-Fi to access this server
server.address=0.0.0.0
  
  # ===============================
  # POSTGRESQL DATABASE (Persistent)
  # ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/kefi_db
spring.datasource.username=kefi_admin
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver
  
  # Hibernate automatically creates/updates SQL tables based on our Java Classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
  
  # ===============================
  # REDIS CONFIGURATION (In-Memory/WebSockets)
  # ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
  
  # ===============================
  # LOGGING
  # ===============================
logging.level.org.springframework.web=INFO

# ===============================
# SPOTIFY API CONFIGURATION
# ===============================
spotify.client.id=4c5f4691e2f6402aa8216ddf8441869f
spotify.client.secret= 4730072014144dd5bd57c8fd48842880